lenient: true

line_length:
  warning: 250
  error: 300

file_length:
  warning: 1500
  error: 1750

type_body_length:
  warning: 600

function_body_length:
  warning: 600

opt_in_rules:
  - indentation_width

indentation_width:
  indentation_width: 2

excluded:
  - .build
  - Package.swift
  - Pods
  - Carthage
  - Source/ExcludedFolder